CREATE TABLE usuario(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR(100),
    senha VARCHAR(200),
    email VARCHAR(50),
    nome_completo VARCHAR(100),
    foto_perfil bytea,
    ultima_atualizacao DATE
);
CREATE TABLE anuncio(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT references usuario(id),
    titulo VARCHAR(50),
    descricao VARCHAR(300),
    tipo_anuncio VARCHAR(50),
    disponibilidade BOOLEAN,
    preco DECIMAL(10,2),
    data_hora_publicacao DATE,
    foto_anuncio bytea
);
CREATE TABLE amizade(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seguidor_id INT references usuario(id),
    seguido_id INT references usuario(id),
    data_hora_inicio DATE,
    data_hora_fim DATE,
    amigos BOOLEAN
);
CREATE TABLE carrinho(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT references usuario(id)
);
CREATE TABLE compra(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(50),
    descricao VARCHAR(100),
    usuario_id INT references usuario(id),
    anuncio_id INT references anuncio(id),
    preco DECIMAL(10,2),
    data_hora_compra DATE
);
CREATE TABLE configuracao(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT references usuario(id),
    perfil_publico BOOLEAN,
    acessibilidade BOOLEAN,
    ultima_atualizacao DATE
);
CREATE TABLE doacao(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(50),
    descricao VARCHAR(100),
    usuario_id INT references usuario(id),
    anuncio_id INT references anuncio(id),
    data_hora_doacao DATE,
    FOREIGN KEY(usuario_id) references usuario(id),
    FOREIGN KEY(anuncio_id) references anuncio(id)
);
CREATE TABLE perfil(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT references usuario(id),
    numero_anuncios INT,
    numero_seguidores INT,
    numero_seguindo INT,
    foto_perfil bytea,
    data_cadastro DATE
);
CREATE TABLE produto(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anuncio_id INT references anuncio(id),
    carrinho_id INT references carrinho(id),
    data_hora_produto_adicionado DATE
);
CREATE TABLE recebimento(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(50),
    descricao VARCHAR(100),
    usuario_id INT references usuario(id),
    anuncio_id INT references anuncio(id),
    data_hora_recebimento DATE
);
CREATE TABLE solicitacao_amizade(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitante_id INT references usuario(id),
    recebe_id INT references usuario(id),
    data_hora_solicitacao DATE,
    data_hora_aprovacao DATE,
    data_hora_delecao DATE,
    amizade_aprovada BOOLEAN
);
CREATE TABLE venda(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(50),
    descricao VARCHAR(100),
    usuario_id INT references usuario(id),
    anuncio_id INT references anuncio(id),
    preco DECIMAL(10,2),
    data_hora_venda DATE
);